#!/bin/sh
. /etc/profile.d/instruqt-env.sh

# Install dependencies
sleep 1
/sbin/apk add --update-cache curl vim nano bash wget jq openssh-client sshpass busybox-extras

# Create example file on Windows host
while ! nc -z windows 22; do
  echo "Waiting for SSH to be available"
  sleep 1
done
/usr/bin/sshpass -e ssh -o 'StrictHostKeyChecking=no' instruqt@windows 'New-Item -Path C:/ -Name example.txt -Value "Hello Windows"'

# Wait until RDP is available
while ! nc -z windows 3389; do
  echo "Waiting for RDP to be available"
  sleep 1
done
