version: "3"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
virtualmachines:
- name: windows
  image: instruqt/windows-server
  machine_type: n1-standard-2
