version: "2"
containers:
- name: guac
  image: gcr.io/instruqt/guacamole
  shell: /bin/bash
  ports:
  - 8080
- name: powershell
  image: mcr.microsoft.com/powershell
  shell: /opt/microsoft/powershell/7/pwsh
  memory: 512
virtualmachines:
- name: windows
  image: instruqt/windows-server
  machine_type: n1-standard-2
